services:
  - type: web
    name: meesho-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false  # Set this manually in Render dashboard
      - key: CORS_ORIGIN
        sync: false  # Set this manually in Render dashboard
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health
